name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> "${GITHUB_OUTPUT}"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Set custom CNAME
        id: set-cname
        run: echo "PAGE_CNAME=$(echo '${{ github.repository }}' | awk -F'/' '{print $2}').hbrown-test.com" >> $GITHUB_ENV

      - name: Check CNAME and HTTPS enforcement
        id: check-https
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          OWNER=$(echo $REPO | awk -F'/' '{print $1}')
          REPO_NAME=$(echo $REPO | awk -F'/' '{print $2}')
          RESPONSE=$(curl -L -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$OWNER/$REPO_NAME/pages)
          CNAME=$(echo $RESPONSE | jq -r '.cname')
          HTTPS_ENFORCED=$(echo $RESPONSE | jq -r '.https_enforced')
          if [ "$CNAME" != "null" ]; then
            echo "CNAME_EXISTS=true" >> $GITHUB_ENV
          else
            echo "CNAME_EXISTS=false" >> $GITHUB_ENV
          fi
          if [ "$HTTPS_ENFORCED" == "true" ]; then
            echo "HTTPS_ENFORCED=true" >> $GITHUB_ENV
          else
            echo "HTTPS_ENFORCED=false" >> $GITHUB_ENV
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          force_orphan: true
          allow_empty_commit: true
          cname: mypage9.hbrown-test.com

      - name: Enable Enforce HTTPS
        if: env.CNAME_EXISTS == 'false' || env.HTTPS_ENFORCED == 'false'
        env:
          HTTPS_TOKEN: ${{ secrets.GHP_DEPLOY_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          OWNER=$(echo $REPO | awk -F'/' '{print $1}')
          REPO_NAME=$(echo $REPO | awk -F'/' '{print $2}')
          MAX_RETRIES=30
          RETRY_INTERVAL=30
          for ((i=1; i<=MAX_RETRIES; i++)); do
            echo "Attempt $i to enforce HTTPS"
            RESPONSE=$(curl -L -s -o response.json -w "%{http_code}" \
              -X PUT \
              -H "Authorization: token $HTTPS_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$OWNER/$REPO_NAME/pages \
              -d '{"https_enforced": true}')
            HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
            if [[ "$HTTP_STATUS" == "204" ]]; then
              echo "HTTPS enforcement successful"
              cat response.json
              break
            else
              echo "HTTPS enforcement failed with status $HTTP_STATUS. Retrying in $RETRY_INTERVAL seconds..."
              cat response.json
              sleep $RETRY_INTERVAL
            fi
          done
          if [[ "$HTTP_STATUS" != "204" ]]; then
            echo "Failed to enforce HTTPS after $MAX_RETRIES attempts."
            exit 1
          fi
